In [16]:
import torch
from torchrl.data import ReplayBuffer, LazyTensorStorage

buf = ReplayBuffer(storage=LazyTensorStorage(
                    max_size=5,
                    device='cuda'),
                    batch_size=2)        # Sample 2 trajectories each time.

trajectory1 = (torch.as_tensor(1), torch.as_tensor(2), torch.as_tensor(3), torch.as_tensor(4))    # S, A, R, S
trajectory2 = (torch.as_tensor(5), torch.as_tensor(6), torch.as_tensor(7), torch.as_tensor(8))
trajectory3 = (torch.as_tensor(9), torch.as_tensor(10), torch.as_tensor(11), torch.as_tensor(12))

buf.add(trajectory1)
buf.add(trajectory2)
buf.add(trajectory3)

buf.sample()     # prints state batch, action batch, reward batch and next state batch.


(tensor([5, 1], device='cuda:0'),
 tensor([6, 2], device='cuda:0'),
 tensor([7, 3], device='cuda:0'),
 tensor([8, 4], device='cuda:0'))